export class IVA {
    constructor(
        public categoria: string,
        public casillero: string,
        public base_enero: number,
        public iva_enero: number,
        public base_febrero: number,
        public iva_febrero: number,
        public base_marzo: number,
        public iva_marzo: number,
        public base_abril: number,
        public iva_abril: number,
        public base_mayo: number,
        public iva_mayo: number,
        public base_junio: number,
        public iva_junio: number,
        public base_julio: number,
        public iva_julio: number,
        public base_agosto: number,
        public iva_agosto: number,
        public base_septiembre: number,
        public iva_septiembre: number,
        public base_octubre: number,
        public iva_octubre: number,
        public base_noviembre: number,
        public iva_noviembre: number,
        public base_diciembre: number,
        public iva_diciembre: number,
        public base_primer_semestre: number,
        public iva_primer_semestre: number,
        public base_segundo_semestre: number,
        public iva_segundo_semestre: number,
        public base_anual: number,
        public iva_anual: number,
    ) { }
}