export interface FormFactura {
    //id_factura_compra: number,
    id_proveedor: number,
    id_forma_pago: number,
    id_asiento: number,
    id_info_tributaria: number,
    clave_acceso: string,
    codigo: string,
    fecha_emision: Date,
    fecha_vencimiento: Date,
    estado_pago: string,
    total_sin_impuesto: number,
    total_descuento: number,
    iva: number,
    propina: number,
    importe_total: number,
    abono: number,
    saldo: number,
}

